In [ ]:
from google.colab import files
uploaded = files.upload()

Saving urdu_comments.csv to urdu_comments.csv

In [ ]:
import pandas as pd
import re
import string

In [ ]:
import pandas as pd
urdu = pd.read_csv('urdu_comments.csv',encoding="utf-16", delimiter='\t')
urdu.head()

                                             comment sentiment
0  اللہ آپکو سلامت رکھے جزائے خیر عطا فرمائے اور ...  positive
1                                  اللہ سب سے بڑا ہے  positive
2  سید محسن رضا نقوی پر یقین کرنے کو دل کرتا ھے ک...  positive
3          نیازی خان ہیرو ثابت ہوا جیسے بڑوں گی مرضی  positive
4                          آپ کی عظمت کو سلام شاہ جی  positive

In [ ]:
urdu.shape

(7095, 2)

In [ ]:
print(urdu.index)

RangeIndex(start=0, stop=7095, step=1)

Remove HTML **Tags**

In [ ]:
import re
def remove_html_tags(text):
      if not isinstance(text, str):
        return ""
      pattern = re.compile('<.*?>')
      return pattern.sub(r'', text)

In [ ]:
urdu['comment'] = urdu['comment'].apply(remove_html_tags)

Remove **URLs**

In [ ]:
def remove_urls(text):
    if not isinstance(text, str):
        return ""

    # Handles http, https, www, and common URL patterns
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

urdu['comment'] = urdu['comment'].apply(remove_urls)

**Punctuations**

In [ ]:
def remove_punctuation(text):
    if not isinstance(text, str):
        return ""

    # Remove everything except ۔ (Urdu full stop)
    pattern = re.compile(r'[!"#$%&\'()*+,-./:;<=>?@[\\\]^_`{|}~،؛؟]')
    return pattern.sub(' ', text)

urdu['comment'] = urdu['comment'].apply(remove_punctuation)

Chatwords **treatment**

In [ ]:
urdu_chatwords = {
    "plz": "براہ مہربانی",
    "pls": "براہ مہربانی",
    "tnx": "شکریہ",
    "thx": "شکریہ",
    "ws": "وعلیکم السلام",
    "as": "السلام علیکم",
    "asl": "السلام علیکم",
    "g": "جی",
    "ya": "یا",
    "uae": "متحدہ عرب امارات",
    "u": "آپ",
    "r": "ہیں",
    "bt": "لیکن",
    "bcoz": "کیوں کہ",
    "bc": "کیوں کہ",
    "fr": "کے لیے",
    "4": "کے لیے",
    "m": "میں",
    "me": "میں",
    "hn": "ہاں",
    "ha": "ہاں",
    "nahi": "نہیں",
    "nai": "نہیں",
    "ni": "نہیں",
    "q": "کیوں",
    "kn": "کچھ نہیں",
    "gd": "اچھا",
    "nyc": "اچھا",
    "awsm": "زبردست",
    "hru": "آپ کیسے ہیں",
    "wyd": "کیا کر رہے ہو",
    "idk": "مجھے نہیں معلوم",
    "omg": "اوہ میرے خدا",
    "lol": "ہنسی",
    "jk": "مزاق کر رہا ہوں",
    "kb": "کب",
    "abhi": "ابھی",
    "agr": "اگر",
    "mgr": "مگر",
    "lekin": "لیکن",
    "phr": "پھر",
    "kl": "کل",
    "aj": "آج",
    "mj": "مجھے",
    "tm": "تم",
    "ap": "آپ",
    "bh": "بھی",
    "bs": "بس"
}

In [ ]:
def chat_conversion(text):
    if not isinstance(text, str):
        return ""

    new_text = []
    for w in text.split():
        if w.upper() in urdu_chatwords:
            new_text.append(urdu_chatwords[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

urdu['comment'] = urdu['comment'].apply(chat_conversion)

In [ ]:
urdu['comment'] = urdu['comment'].apply(chat_conversion)

Handling Emojis

In [ ]:
import re

def remove_emoji(text):
    if not isinstance(text, str):
        return ""

    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

urdu['comment'] = urdu['comment'].apply(remove_emoji)

Tokenization

In [ ]:
from nltk.tokenize import word_tokenize, sent_tokenize
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

urdu['tokens'] = urdu['comment'].apply(lambda x: x.split())
display(urdu[['comment', 'tokens']].head(3))

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

,comment,tokens
0,اللہ آپکو سلامت رکھے جزائے خیر عطا فرمائے اور ...,"[اللہ, آپکو, سلامت, رکھے, جزائے, خیر, عطا, فرم..."
1,اللہ سب سے بڑا ہے,"[اللہ, سب, سے, بڑا, ہے]"
2,سید محسن رضا نقوی پر یقین کرنے کو دل کرتا ھے ک...,"[سید, محسن, رضا, نقوی, پر, یقین, کرنے, کو, دل,..."

In [ ]:
from google.colab import files

# Save and download
urdu.to_csv('final_urdu_dataset.csv', index=False, encoding='utf-8-sig')
files.download('final_urdu_dataset.csv')

print("File downloaded successfully!")

File downloaded successfully!