In [10]:
from google.colab import files
uploaded = files.upload()

Saving Roman Urdu DataSet.csv to Roman Urdu DataSet (1).csv

In [11]:
import pandas as pd
import re
import string

In [12]:
romanurdu = pd.read_csv('Roman Urdu DataSet.csv')
romanurdu.head()

                                             comment sentiment Unnamed: 2
0  Sai kha ya her kisi kay bus ki bat nhi hai lak...  Positive        NaN
1                                          sahi bt h  Positive        NaN
2                                        Kya bt hai,  Positive        NaN
3                                         Wah je wah  Positive        NaN
4                               Are wha kaya bat hai  Positive        NaN

In [13]:
romanurdu.shape

(11299, 3)

In [14]:
print(romanurdu.index)

RangeIndex(start=0, stop=11299, step=1)

Lowercasing

In [15]:
# If there are NaN values, .str.lower() handles them well
romanurdu['comment'] = romanurdu['comment'].str.lower()
romanurdu['sentiment'] = romanurdu['sentiment'].str.lower()

# Check results
print(romanurdu[['comment', 'sentiment']].head())

                                             comment sentiment
0  sai kha ya her kisi kay bus ki bat nhi hai lak...  positive
1                                          sahi bt h  positive
2                                        kya bt hai,  positive
3                                         wah je wah  positive
4                               are wha kaya bat hai  positive

Remove HTML Tags

In [16]:
def remove_html_tags(text):
    """Remove HTML tags from text"""
    if not isinstance(text, str):
        return ""

    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

# Apply to dataframe
romanurdu['comment'] = romanurdu['comment'].apply(remove_html_tags)

# Check results
print(romanurdu[['comment']].head())

                                             comment
0  sai kha ya her kisi kay bus ki bat nhi hai lak...
1                                          sahi bt h
2                                        kya bt hai,
3                                         wah je wah
4                               are wha kaya bat hai

Rmove urls

In [17]:
import re

def remove_urls(text):
    """Remove URLs from text"""
    if not isinstance(text, str):
        return ""

    pattern = re.compile(r'http\S+|www\S+|https\S+')
    return pattern.sub(r'', text)

# Apply to dataframe
romanurdu['comment'] = romanurdu['comment'].apply(remove_urls)

# Check results
print(romanurdu[['comment']].head())

                                             comment
0  sai kha ya her kisi kay bus ki bat nhi hai lak...
1                                          sahi bt h
2                                        kya bt hai,
3                                         wah je wah
4                               are wha kaya bat hai

Punctuations

In [18]:
import re
import string

def remove_punctuation(text):
    """Remove English and common punctuation from Roman Urdu text"""
    if not isinstance(text, str):
        return ""

    # Remove all English punctuation
    pattern = re.compile(r'[!"#$%&\'()*+,-./:;<=>?@[\\\]^_`{|}~]')
    return pattern.sub(' ', text)

# Apply to dataframe
romanurdu['comment'] = romanurdu['comment'].apply(remove_punctuation)

# Check results
print(romanurdu[['comment']].head())

                                             comment
0  sai kha ya her kisi kay bus ki bat nhi hai lak...
1                                          sahi bt h
2                                        kya bt hai
3                                         wah je wah
4                               are wha kaya bat hai

Chatwords treatment

In [19]:
chat_words = {
    "u": "you",
    "r": "are",
    "ur": "your",
    "k": "kay",
    "ki": "ki",
    "ka": "ka",
    "pls": "please",
    "plz": "please",
    "ppl": "people",
    "msg": "message",
    "tmrw": "tomorrow",
    "gm": "good morning",
    "gn": "good night",
    "tc": "take care",
    "bt": "but",
    "bcoz": "because",
    "bc": "because",
    "fr": "for",
    "4": "for",
    "gr8": "great",
    "m": "main",
    "me": "main",
    "hn": "haan",
    "ha": "haan",
    "h": "haan",
    "ap": "aap",
    "thx": "thanks",
    "tnx": "thanks",
    "gud": "good",
    "nyc": "nice",
    "bro": "bhai",
    "sis": "behen",
    "lol": "laugh",
    "omg": "oh my god",
    "idk": "i dont know",
    "ikr": "i know right",
    "wtf": "what the f",
    "wth": "what the hell",
    "smh": "shaking my head",
    "afaik": "as far as i know",
    "imo": "in my opinion",
    "jk": "just kidding"
}

def chat_conversion(text):
    if not isinstance(text, str):
        return ""

    new_text = []
    for w in text.split():
        if w.lower() in chat_words:  # Changed to .lower()
            new_text.append(chat_words[w.lower()])
        else:
            new_text.append(w)
    return " ".join(new_text)

romanurdu['comment'] = romanurdu['comment'].apply(chat_conversion)

Handling Emojis

In [20]:
import re

def remove_emoji(text):
    """Remove emojis from Roman Urdu text"""
    if not isinstance(text, str):
        return ""

    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

# Apply to dataframe
romanurdu['comment'] = romanurdu['comment'].apply(remove_emoji)

# Check results
print(romanurdu[['comment']].head())

                                             comment
0  sai kha ya her kisi kay bus ki bat nhi hai lak...
1                                      sahi but haan
2                                        kya but hai
3                                         wah je wah
4                               are wha kaya bat hai

Tokenization

In [21]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('punkt_tab')
romanurdu["tokens"] = romanurdu["comment"].apply(lambda x: word_tokenize(str(x)))

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [22]:
display(romanurdu[['comment', 'tokens']].head())

,comment,tokens
0,sai kha ya her kisi kay bus ki bat nhi hai lak...,"[sai, kha, ya, her, kisi, kay, bus, ki, bat, n..."
1,sahi but haan,"[sahi, but, haan]"
2,kya but hai,"[kya, but, hai]"
3,wah je wah,"[wah, je, wah]"
4,are wha kaya bat hai,"[are, wha, kaya, bat, hai]"

In [23]:
from google.colab import files

# Save and download
romanurdu.to_csv('final_roman_urdu_dataset.csv', index=False, encoding='utf-8-sig')
files.download('final_roman_urdu_dataset.csv')

print("File downloaded successfully!")

File downloaded successfully!