In [ ]:
  from google.colab import files
uploaded = files.upload()

Saving Roman Urdu DataSet.csv to Roman Urdu DataSet (1).csv
Saving urdu_comments.csv to urdu_comments (1).csv

In [ ]:
import pandas as pd
romanurdu = pd.read_csv('Roman Urdu DataSet.csv')
romanurdu.head()

                                             comment sentiment Unnamed: 2
0  Sai kha ya her kisi kay bus ki bat nhi hai lak...  Positive        NaN
1                                          sahi bt h  Positive        NaN
2                                        Kya bt hai,  Positive        NaN
3                                         Wah je wah  Positive        NaN
4                               Are wha kaya bat hai  Positive        NaN

In [ ]:
urdu = pd.read_csv("urdu_comments.csv", encoding="utf-16", delimiter='\t')
urdu.head()

                                             comment sentiment
0  اللہ آپکو سلامت رکھے جزائے خیر عطا فرمائے اور ...  positive
1                                  اللہ سب سے بڑا ہے  positive
2  سید محسن رضا نقوی پر یقین کرنے کو دل کرتا ھے ک...  positive
3          نیازی خان ہیرو ثابت ہوا جیسے بڑوں گی مرضی  positive
4                          آپ کی عظمت کو سلام شاہ جی  positive

In [ ]:
romanurdu.shape

(11299, 3)

In [ ]:
urdu.shape

(7095, 2)

In [ ]:
print(romanurdu.index)

RangeIndex(start=0, stop=11299, step=1)

In [ ]:
print(urdu.index)

RangeIndex(start=0, stop=7095, step=1)

REMOVE_EMPTY_ROWS

In [ ]:
# Remove rows where comment is NaN or empty string or just spaces
romanurdu = romanurdu[romanurdu['comment'].notna()]
romanurdu = romanurdu[romanurdu['comment'].str.strip() != ""]

urdu = urdu[urdu['comment'].notna()]
urdu = urdu[urdu['comment'].str.strip() != ""]

In [ ]:
print("Roman Urdu rows:", len(romanurdu))
print("Urdu rows:", len(urdu))

Roman Urdu rows: 11299
Urdu rows: 7095

LOWERCASING

In [ ]:
romanurdu['comment'] = romanurdu['comment'].str.lower()
romanurdu['sentiment'] = romanurdu['sentiment'].str.lower()
romanurdu[['comment','sentiment']].head()

                                             comment sentiment
0  sai kha ya her kisi kay bus ki bat nhi hai lak...  positive
1                                          sahi bt h  positive
2                                        kya bt hai,  positive
3                                         wah je wah  positive
4                               are wha kaya bat hai  positive

REMOVE_HTML_TAGS

In [ ]:
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

In [ ]:
romanurdu['comment'] = romanurdu['comment'].apply(remove_html_tags)

In [ ]:
urdu['comment'] = urdu['comment'].apply(remove_html_tags)

REMOVE_URLS

In [ ]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [ ]:
romanurdu['comment'] = romanurdu['comment'].apply(remove_url)

In [ ]:
urdu['comment'] = urdu['comment'].apply(remove_url)

REMOVE_PUNCTUATIONS

In [ ]:
import string,time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
exclude = string.punctuation
def remove_punc(text):
    for char in exclude:
        text = text.replace(char,'')
    return text

In [ ]:
romanurdu['comment'] = romanurdu['comment'].apply(remove_punc)

In [ ]:
urdu['comment'] = urdu['comment'].apply(remove_punc)

CHATWORDS_TREATMENT

In [ ]:
chat_words = {
    "u": "you",
    "r": "are",
    "ur": "your",
    "k": "kay",
    "ki": "ki",
    "ka": "ka",
    "pls": "please",
    "plz": "please",
    "ppl": "people",
    "msg": "message",
    "tmrw": "tomorrow",
    "gm": "good morning",
    "gn": "good night",
    "tc": "take care",
    "bt": "but",
    "bcoz": "because",
    "bc": "because",
    "fr": "for",
    "4": "for",
    "gr8": "great",
    "m": "main",
    "me": "main",
    "hn": "haan",
    "ha": "haan",
    "h": "haan",
    "ap": "aap",
    "thx": "thanks",
    "tnx": "thanks",
    "gud": "good",
    "nyc": "nice",
    "bro": "bhai",
    "sis": "behen",
    "lol": "laugh",
    "omg": "oh my god",
    "idk": "i dont know",
    "ikr": "i know right",
    "wtf": "what the f",
    "wth": "what the hell",
    "smh": "shaking my head",
    "afaik": "as far as i know",
    "imo": "in my opinion",
    "jk": "just kidding"
}
urdu_chatwords = {
    "plz": "براہ مہربانی",
    "pls": "براہ مہربانی",
    "tnx": "شکریہ",
    "thx": "شکریہ",
    "ws": "وعلیکم السلام",
    "as": "السلام علیکم",
    "asl": "السلام علیکم",
    "g": "جی",
    "ya": "یا",
    "uae": "متحدہ عرب امارات",
    "u": "آپ",
    "r": "ہیں",
    "bt": "لیکن",
    "bcoz": "کیوں کہ",
    "bc": "کیوں کہ",
    "fr": "کے لیے",
    "4": "کے لیے",
    "m": "میں",
    "me": "میں",
    "hn": "ہاں",
    "ha": "ہاں",
    "nahi": "نہیں",
    "nai": "نہیں",
    "ni": "نہیں",
    "q": "کیوں",
    "kn": "کچھ نہیں",
    "gd": "اچھا",
    "nyc": "اچھا",
    "awsm": "زبردست",
    "hru": "آپ کیسے ہیں",
    "wyd": "کیا کر رہے ہو",
    "idk": "مجھے نہیں معلوم",
    "omg": "اوہ میرے خدا",
    "lol": "ہنسی",
    "jk": "مزاق کر رہا ہوں",
    "kb": "کب",
    "abhi": "ابھی",
    "agr": "اگر",
    "mgr": "مگر",
    "lekin": "لیکن",
    "phr": "پھر",
    "kl": "کل",
    "aj": "آج",
    "mj": "مجھے",
    "tm": "تم",
    "ap": "آپ",
    "bh": "بھی",
    "bs": "بس"
}

In [ ]:
all_chatwords = {**chat_words, **urdu_chatwords}

def chat_conversion(text):
    new_words = []
    for w in text.split():
        key = w.lower()
        if key in all_chatwords:
            new_words.append(all_chatwords[key])
        else:
            new_words.append(w)
    return " ".join(new_words)

In [ ]:
romanurdu['comment'] = romanurdu['comment'].apply(chat_conversion)

In [ ]:
all_chatwords = {**chat_words, **urdu_chatwords}

def chat_conversion(text):
    new_text = []
    for w in text.split():
        key = w.lower()
        if key in all_chatwords:
            new_text.append(all_chatwords[key])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [ ]:
urdu['comment'] = urdu['comment'].apply(chat_conversion)

HANDLE_IMOJIS

In [ ]:
emoji_dict = {
    "😂": "positive",
    "🤣": "positive",
    "😊": "positive",
    "😍": "positive",
    "❤️": "positive",
    "💖": "positive",
    "👍": "positive",
    "🔥": "positive",

    "😡": "negative",
    "😠": "negative",
    "💔": "negative",
    "😢": "negative",
    "😭": "negative",
    "👎": "negative",
}

In [ ]:
def handle_emoji(text):
    for emo, meaning in emoji_dict.items():
        text = text.replace(emo, meaning)
    return text

In [ ]:
romanurdu['comment'] = romanurdu['comment'].apply(handle_emoji)

In [ ]:
urdu['comment'] = urdu['comment'].apply(handle_emoji)

REMOVE_STOPWORDS

In [ ]:
roman_stopwords = [
"hai","han","ha","h","hue","kya","kyu","kyun","ki","ka","ke","ko","se","me","mein","tum",
"mujhe","mera","meri","wo","woh","ye","yeh","tha","thi","the","aur","lekin","magar","bhi","jab",
"tak","phir","to","na","nahi","nai","ni","hum","ap","aap","tumhari","tumhare","tumhe","tumhi",
"mera","meri","mere","apka","apki","apke","tha","thi","the","hain","hai","ha","ho","hu","hoon",
"raha","rahi","rahe","kar","karta","karti","karte","kr","krta","krti","krte","mera","meri","mere",
"kaun","kahan","kab","kis","kuch","kisi","kya","kahan","kaise","ka","ke","ki","ko","se","mein","me",
"tum","tumne","tumhara","tumhari","tumhare","mujhe","mujh","mera","meri","mere","hum","hamne","hamari",
"hamare","ap","aapne","aapka","aapki","aapke","woh","usne","unka","unki","unke","ye","yeh","in","inne",
"isse","iske","is","hain","hai","ha","h","hu","ho","hoon","raha","rahi","rahe","kar","karta","karti",
"karte","kr","krta","krti","krte","ko","ke","ka","mein","me","na","nahi","nai","ni","to","tak",
"phir","aur","ya","yaani","magar","lekin","bhi","jab","kuch","kisi","kya","kab","kaun","kaise",
"kis","mein","me","tum","tumhe","tumhi","mera","meri","mere","apka","apki","apke","tumhari","tumhare",
"tumharey","hamara","hamari","hamare","unka","unki","unke","aap","apka","apki","apke","hain","hai",
"ha","h","ho","hu","hoon","raha","rahi","rahe","kar","karta","karti","karte","kr","krta","krti",
"krte","ne","ko","ke","ka","se","mein","me","nahin","nai","ni","phir","aur","ya","magar","lekin",
"bhi","jab","tak","kaun","kab","kya","kaise","kis","kahan","tumhara","tumhari","tumhare","mera",
"meri","mere","apka","apki","apke","hamara","hamari","hamare","unka","unki","unke","yeh","ye","woh",
"wo","isme","iske","usme","uske","inme","inke","unne","unka","unki"
]
urdu_stopwords = [
"ہے","ہوں","ہیں","تھا","تھی","تھے","کر","کیا","کیوں","کی","کا","کے","کو",
"سے","میں","تم","ہم","آپ","وہ","یہ","اس","اور","لیکن","اگر","مگر","پھر",
"بھی","جب","تک","بعد","ہوا","ہوتا","ہوتی","نے","پر","کا","کی","کے","کیوں",
"کہ","ہے","ہوں","ہیں","تھا","تھی","تھے","کر","کیا","کیوں","کا","کی","کے",
"کو","سے","میں","تم","ہم","آپ","وہ","یہ","اس","اور","لیکن","اگر","مگر","پھر",
"بھی","جب","تک","بعد","ہوا","ہوتا","ہوتی","نے","پر","ہے","ہوں","ہیں","تھا",
"تھی","تھے","کر","کیا","کیوں","کا","کی","کے","کو","سے","میں","تم","ہم","آپ",
"وہ","یہ","اس","اور","لیکن","اگر","مگر","پھر","بھی","جب","تک","بعد","ہوا",
"ہوتا","ہوتی","نے","پر","کا","کی","کے","کیوں","کہ","ہے","ہوں","ہیں","تھا",
"تھی","تھے","کر","کیا","کیوں","کا","کی","کے","کو","سے","میں","تم","ہم","آپ",
"وہ","یہ","اس","اور","لیکن","اگر","مگر","پھر","بھی","جب","تک","بعد","ہوا",
"ہوتا","ہوتی","نے","پر","کا","کی","کے","کیوں","کہ","ہے","ہوں","ہیں","تھا",
"تھی","تھے","کر","کیا","کیوں"
]

In [ ]:
import re
import string

def remove_stopwords(text):
    text = text.lower()

    text = re.sub(r'[^\w\s]', ' ', text)

    words = text.split()

    filtered = []
    for w in words:
        if w not in roman_stopwords and w not in urdu_stopwords:
            filtered.append(w)

    return " ".join(filtered)

In [ ]:
romanurdu['comment'] = romanurdu['comment'].apply(remove_stopwords)

In [ ]:
urdu['comment'] = urdu['comment'].apply(remove_stopwords)

ROMAN_URDU_NORMALIZATION

In [ ]:
roman_normalization = {
    "acha": "acha",
    "achaa": "acha",
    "achaaa": "acha",
    "achaah": "acha",
    "achaaaa": "acha",

    "bohat": "bohat",
    "boht": "bohat",
    "bhot": "bohat",
    "buhat": "bohat",
    "bouhat": "bohat",

    "zyada": "zyada",
    "zada": "zyada",
    "ziada": "zyada",
    "ziyadha": "zyada",

    "nahi": "nahi",
    "nai": "nahi",
    "ni": "nahi",
    "neh": "nahi",
    "nehi": "nahi",
    "nh": "nahi",

    "haan": "haan",
    "han": "haan",
    "ha": "haan",
    "hn": "haan",

    "sahi": "sahi",
    "sai": "sahi",
    "sahe": "sahi",
    "sahee": "sahi",

    "galat": "galat",
    "ghalat": "galat",
    "ghlt": "galat",
    "glat": "galat",

    "kya": "kya",
    "kia": "kya",
    "kyaaa": "kya",
    "kyaa": "kya",

    "shukriya": "shukriya",
    "shukria": "shukriya",
    "shkria": "shukriya",
    "shkr": "shukriya",

    "video": "video",
    "vidio": "video",

    "masla": "masla",
    "msla": "masla",
    "maslaa": "masla",

    "khubsurat": "khobsurat",
    "khoobsurat": "khobsurat",
    "khobsrt": "khobsurat",
    "khubsrt": "khobsurat",

    "achaai": "achai",
    "achay": "achay",
    "achy": "achay"
}

In [ ]:
def normalize_roman_urdu(text):
    words = text.split()
    new_words = []

    for w in words:
        w_lower = w.lower()

        if w_lower in roman_normalization:
            new_words.append(roman_normalization[w_lower])
        else:

            w_clean = re.sub(r'(.)\1{2,}', r'\1', w_lower)

            new_words.append(w_clean)

    return " ".join(new_words)

In [ ]:
romanurdu['comment'] = romanurdu['comment'].astype(str).apply(normalize_roman_urdu)

TOKENIZATION

In [ ]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('punkt_tab')

def tokenize_text(text):
    text = str(text)
    tokens = word_tokenize(text)
    return tokens

romanurdu['tokens'] = romanurdu['comment'].apply(tokenize_text)
urdu['tokens'] = urdu['comment'].apply(tokenize_text)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [ ]:
display(romanurdu[['comment','tokens']].head(3))
display(urdu[['comment','tokens']].head(3))

,comment,tokens
0,sahi kha یا her kay bus bat nhi lakin main hal...,"[sahi, kha, یا, her, kay, bus, bat, nhi, lakin..."
1,sahi haan,"[sahi, haan]"
2,,[]

,comment,tokens
0,اللہ آپکو سلامت رکھے جزائے خیر عطا فرمائے حق ب...,"[اللہ, آپکو, سلامت, رکھے, جزائے, خیر, عطا, فرم..."
1,اللہ سب بڑا,"[اللہ, سب, بڑا]"
2,سید محسن رضا نقوی یقین کرنے دل کرتا ھے کیونکہ ...,"[سید, محسن, رضا, نقوی, یقین, کرنے, دل, کرتا, ھ..."

In [ ]:
romanurdu.to_csv('romanurdu_cleaned.csv', index=False, encoding='utf-8-sig')
urdu.to_csv('urdu_cleaned.csv', index=False, encoding='utf-8-sig')
combined = pd.concat([romanurdu.assign(language='roman'),urdu.assign(language='urdu')], ignore_index=True, sort=False)
combined.to_csv('combined_cleaned.csv', index=False, encoding='utf-8-sig')
print("Saved files: romanurdu_cleaned.csv, urdu_cleaned.csv, combined_cleaned.csv")

Saved files: romanurdu_cleaned.csv, urdu_cleaned.csv, combined_cleaned.csv

In [ ]:
from google.colab import files
files.download("combined_cleaned.csv")

FEATURE_ENGINEERING

In [ ]:
#from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=70000,
    ngram_range=(1,2),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True
)



vectorizer = TfidfVectorizer(ngram_range=(1,2))
X = vectorizer.fit_transform(combined["comment"])
y = combined["sentiment"].str.lower()  # normalize labels

SPLITTING_DATASET

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

MODELING

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report

model = LinearSVC(class_weight='balanced')
model.fit(X_train_tfidf, y_train)
y_pred = model.predict(X_test_tfidf)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

NameError: name 'X_train_tfidf' is not defined

CONFUSION_MATRIX

In [ ]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()

CHECKING_PREDICTIONS_ON_URDU_COMMENTS

In [ ]:
def predict_sentiment(text):
    # Clean text (same cleaning you used earlier)
    text = text.lower()

    # Convert to TF-IDF features
    text_tfidf = vectorizer.transform([text])

    # Predict
    pred = model.predict(text_tfidf)[0]

    return pred

# Example Urdu comments to test
test_comments = [
    "یہ چینل بہت اچھا ہے",
    "مجھے یہ ویڈیو پسند نہیں آئی",
    "تمہاری بات بالکل غلط ہے",
    "آپ کا کام بہت زبردست ہے"
]

for c in test_comments:
    print(c, "→", predict_sentiment(c))

CHECKING_PREDICTIONS_ON_ROMAN_URDU_COMMENTS

In [ ]:
test_comments = [
    "Ye channel bohat acha hai",           # positive
    "Mujhe ye video pasand nahi aayi",    # negative
    "Tumhari baat bilkul ghalat hai",     # negative
    "Aap ka kaam bohat zabardast hai",   # positive
    "Ye tutorial samajh nahi aaya",       # negative
    "Bohat hi informative video hai",     # positive
    "Mujhe ye pasand nahi aya",           # negative
    "Wah! bohat achi presentation hai",  # positive
    "Ye content bilkul useless hai",      # negative
    "Video quality bohat acchi hai"       # positive
]

for c in test_comments:
    print(c, "→", predict_sentiment(c))

In [ ]:
import re

# Roman Urdu normalization dictionary
roman_dict = {
    'nahi': 'na',
    'pasandh': 'pasand',
    'acha': 'achha',
    'bohat': 'bahut',
    'zyada': 'ziyada',
    'acchi': 'achhi',
    'zabardast': 'great',
    'samajh': 'samaj',
    'video': 'video',  # example keep same
    'presentation': 'presentation'  # keep as is
    # Tum aur bhi words add kar sakte ho
}

def preprocess_roman_urdu(text):
    # Lowercase
    text = text.lower()

    # Remove unwanted characters
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)

    # Tokenize and normalize
    words = text.split()
    words = [roman_dict.get(w, w) for w in words]  # replace if in dictionary

    # Join back
    clean_text = ' '.join(words)
    return clean_text

# Example usage with your predict function
def predict_sentiment_roman(text):
    text_clean = preprocess_roman_urdu(text)
    text_tfidf = vectorizer.transform([text_clean])
    pred = model.predict(text_tfidf)[0]
    return pred

# Test Roman Urdu comments
test_comments = [
    "Ye channel bohat acha hai",
    "Mujhe ye video pasand nahi aayi",
    "Tumhari baat bilkul ghalat hai",
    "Aap ka kaam bohat zabardast hai"
]

for c in test_comments:
    print(c, "→", predict_sentiment_roman(c))

offline augmentation

In [ ]:
import pandas as pd

df = pd.read_csv('combined_cleaned.csv')
print(df['sentiment'].value_counts())

In [ ]:
import pandas as pd
import random

# Step 1: Load your final dataset
df = pd.read_csv('combined_cleaned.csv')

# Step 2: Define basic Roman Urdu mapping for common words
roman_dict = {
    'یہ': 'ye',
    'ویڈیو': 'video',
    'بہت': 'bohat',
    'اچھی': 'achhi',
    'پسند': 'pasand',
    'نہیں': 'nahi',
    'کام': 'kaam',
    'زبردست': 'zabardast',
    'ٹھیک': 'theek',
    'کامیاب': 'kamyab',
    'ٹیم': 'team',
    'میچ': 'match',
    'ہاں': 'haan',
    'نہیں': 'nahi',
    'ہے': 'hai'
}

# Step 3: Function to convert Urdu comment to Roman Urdu
def to_roman_urdu(comment):
    # Ensure the comment is a string before splitting
    comment_str = str(comment)
    words = comment_str.split()
    roman_words = [roman_dict.get(w, w) for w in words]
    return ' '.join(roman_words)

# Step 4: Minor variations for augmentation
def augment_roman(text):
    words = text.split()

    # Randomly swap two words (10% chance)
    if len(words) > 2 and random.random() < 0.1:
        i, j = random.sample(range(len(words)), 2)
        words[i], words[j] = words[j], words[i]

    # Randomly replace 'bohat' with 'bahut'
    words = ['bahut' if w=='bohat' and random.random()<0.5 else w for w in words]

    # Randomly replace 'achhi' with 'acchi'
    words = ['acchi' if w=='achhi' and random.random()<0.5 else w for w in words]

    return ' '.join(words)

# Step 5: Create Roman Urdu variants
roman_comments = []
sentiments = []

for idx, row in df.iterrows():
    roman = to_roman_urdu(row['comment'])
    augmented = augment_roman(roman)

    roman_comments.append(augmented)
    sentiments.append(row['sentiment'])

# Step 6: Create DataFrame for augmented data
df_roman = pd.DataFrame({
    'comment': roman_comments,
    'sentiment': sentiments
})

# Step 7: Combine with original dataset
df_augmented = pd.concat([df, df_roman], ignore_index=True)

# Step 8: Save final augmented CSV
df_augmented.to_csv('augmented_urdu_dataset.csv', index=False)
print("Augmented dataset saved as 'augmented_urdu_dataset.csv' with", len(df_augmented), "rows")

In [ ]:
import pandas as pd

df = pd.read_csv('augmented_urdu_dataset.csv')
print(df.head())
print(df['sentiment'].value_counts())

In [ ]:
from sklearn.model_selection import train_test_split

X = df['comment']
y = df['sentiment']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)  # optional: limit features
X_train_tfidf = vectorizer.fit_transform(X_train.fillna(''))
X_test_tfidf = vectorizer.transform(X_test.fillna(''))

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test_tfidf)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

In [ ]:
def predict_sentiment_roman(text):
    text_tfidf = vectorizer.transform([text])
    pred = model.predict(text_tfidf)[0]
    return pred

# Example Roman Urdu comments
test_comments = [
    "Ye video bohat achhi hai",
    "Mujhe ye video pasand nahi aayi",
    "Tumhari baat bilkul ghalat hai",
    "Aap ka kaam bohat zabardast hai"
]

for c in test_comments:
    print(c, "→", predict_sentiment_roman(c))